[package]
name = "lazy-find"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
notify = "8.1.0"
ratatui = "0.29.0"
rayon = "1.10.0"
serde = "1.0.219"
tokio = { version = "1.46.1", features = ["full"] }
